version: '3'
services:
  lib_api:
    container_name: lib_api
    image: lib_api:latest

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - published: 7000
        target: 9000
    depends_on:
      - mysql_db
    restart: always
    networks:
      - lib_api_network

  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    restart: always
    networks:
      - lib_api_network

networks:
  lib_api_network:
    name: lib_api_network

volumes:
  lib_api:
    name: lib_api
